# Workflow for deploying WasmJS App to GitHub Pages
name: Deploy WasmJS App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "✅ Checkout code"
        uses: actions/checkout@v4

      - name: "⚙️ Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Optional: keep if you want caching
      - name: "⚙️ Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "🛠️ Build WasmJS App"
        working-directory: ./website
        run: ./gradlew :composeApp:wasmJsBrowserDistribution
        env:
          VERSION: "0.0.0-LOCAL"

      - name: "📄 Configure GitHub Pages"
        uses: actions/configure-pages@v5

      - name: "📤 Upload GitHub Pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/composeApp/build/dist/wasmJs/productionExecutable

      - name: "🚀 Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
